### PR TITLE
Rework of the SignatureCalculator

### PR DESCRIPTION
**Pull request by alexdupre**
Change the AHC-specific SignatureCalculator to be a generic/common way to add a signature http header derived from url and content.

### CODE REVIEW

**Review by eed3si9n — APPROVED** [review]
Thanks for the contribution!

**Comment by alexdupre** [comment]
Great, are you planning to release a 0.3.1 version soon and a new scalaxb version?

**Comment by eed3si9n** [comment]
I probably should release this soon so I can use it from sbt.

**Comment by eed3si9n** [comment]
https://github.com/eed3si9n/gigahorse/releases/tag/v0.3.1 0.3.1 is on its way to Maven Central.

**Pull request merged**
